# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-21 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0004_remove_actividad_imagen'),
        ('movimientos', '0004_auto_20181004_1658'),
        ('clientes', '0005_auto_20190520_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adelanto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ManyToManyField(to='actividades.Actividad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.FormaPago')),
            ],
        ),
    ]
