# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-16 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adelantos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adelanto',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='adelanto',
            name='forma_pago',
        ),
    ]
