# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-21 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20181110_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='es_socio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tutor',
        ),
    ]
